name: Deploy to VPS

on:
  push:
    branches: [ main ] # Ay push l hna ghadi i-t-deploya

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # T-akked men had l-smiya
          script: |
            cd /var/www/c-digital-v2
            git pull origin main
            npm install
            npm run build
            pm2 restart c-digital